/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package blog;

import org.junit.Test;

import java.util.ArrayList;

import static org.junit.Assert.*;

public class AppTest {

    @Test public void testSorting() {
        int[] arr = new int[] {8,4,23,42,16,15};
        assertEquals("[4, 8, 15, 16, 23, 42]", App.sorting(arr));
    }

    @Test public void testSorting2() {
        int[] arr2 = new int[] {20,18,12,8,5,-2};
        assertEquals("[-2, 5, 8, 12, 18, 20]", App.sorting(arr2));
    }

    @Test public void testSorting3() {
        int[] arr3 = new int[] {5,12,7,5,5,7};
        assertEquals("[5, 5, 5, 7, 7, 12]", App.sorting(arr3));
    }

    @Test public void testSorting4() {
        int[] arr4 = new int[] {2,3,5,7,13,11};
        assertEquals("[2, 3, 5, 7, 11, 13]", App.sorting(arr4));
    }
}
