/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package blog2;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test public void testMerge() {
        int[] actual = { 8,4,23,42,16,15};
        int[] expected = { 4, 8, 15, 16, 23, 42};
        App.mergeSort(actual);
        assertArrayEquals(expected, actual);
    }

    @Test public void testMerge2() {
        int[] actual = { 20,18,12,8,5,-2};
        int[] expected = { -2, 5, 8, 12, 18, 20};
        App.mergeSort(actual);
        assertArrayEquals(expected, actual);
    }

    @Test public void testMerge3() {
        int[] actual = { 5,12,7,5,5,7};
        int[] expected = { 5, 5, 5, 7, 7, 12};
        App.mergeSort(actual);
        assertArrayEquals(expected, actual);
    }

    @Test public void testMerge4() {
        int[] actual = { 2,3,5,7,13,11};
        int[] expected = { 2, 3, 5, 7, 11, 13};
        App.mergeSort(actual);
        assertArrayEquals(expected, actual);
    }

}
