/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package blog3;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testQuickSort() {

        int arr[] = {8,4,23,42,16,15};
        int n = arr.length;
        App.QuickSort(arr, 0, n-1);

        System.out.println("sorted array");

        assertEquals("42 ", App.printArray(arr));
    }

    @Test public void testQuickSort2() {

        int arr[] = {20,18,12,8,5,-2};
        int n = arr.length;
        App.QuickSort(arr, 0, n-1);

        System.out.println("sorted array");

        assertEquals("20 ", App.printArray(arr));
    }

    @Test public void testQuickSort3() {

        int arr[] = {5,12,7,5,5,7};
        int n = arr.length;
        App.QuickSort(arr, 0, n-1);

        System.out.println("sorted array");

        assertEquals("12 ", App.printArray(arr));
    }

    @Test public void testQuickSort4() {

        int arr[] = {2,3,5,7,13,11};
        int n = arr.length;
        App.QuickSort(arr, 0, n-1);

        System.out.println("sorted array");

        assertEquals("13 ", App.printArray(arr));
    }
}
