/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package blog;

import java.util.ArrayList;

public class App {

    public static void main(String[] args) {

    }

    public static int[] sorting(int[] arr){

        if(arr == null){
            throw new IllegalArgumentException("Null array cannot be sorted!");
        }

        if(arr == null){
            throw new IllegalArgumentException("Null array cannot be sorted!");
        }

        for(int i = 1; i < arr.length; i++){
            int j = i - 1;
            int temp = arr[i];
            while(j >= 0 && temp < arr[j]){
                arr[j + 1] = arr[j];
                j -= 1;
            }

            arr[j + 1] = temp;
        }

        return arr;
    }
}

