/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rpeatedWord;

import java.util.HashSet;
import java.util.Set;

public class RepeatedWord {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new RepeatedWord().getGreeting());
    }

    public static String getFirstFrequentWord(String input){

        if (input == ""){
            return "Empty String.";
        }

        if (input == null){
            return null;
        }

        if(input != null) {

            Set<String> words = new HashSet<String>();
            String[] splitWords = input.toLowerCase().split("\\W+");
            for (String word : splitWords) {

                if (words.contains(word)) {
                    return word;
                } else {
                    words.add(word);
                }
            }
            System.out.println(splitWords[0]);
//            return splitWords[0];
        }
        return "No repeated word!";
    }
}
