/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package data.structure;

import java.util.LinkedList;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    Node head;
    public Library(){
        head = null;
    }

    static class Node {

        int value;
        Node next;
        Node previous;
        Node last;
        public Node(int v){
            value = v;
            next = null;
            previous = null;
            last = null;
        }
    }

    public void insert(int data) {
        Node node = new Node(data);
        if (head == null) {
            head = node;
        }else{
            node.next = head;
            head = node;
        }
    }

    public void append(int val) {
        Node value = new Node(val);
        if (head == null) {
            head = value;
        } else {
            Node current = head;
            while (current.next != null) {
                current = current.next;
            }
            current.next = value;
        }
    }

    public void insertAfter(int value, int newValue){
            Node node = new Node(newValue);
            Node current = head;
            while(current.value != value && current.next != null){
                current = current.next;
            }
            node.next = current.next;
            current.next = node;
        }

    public String toString() {
        Node currNode = head;
        String result = "";

        while (currNode != null) {
            result+="{" + currNode.value + "} -> ";
            currNode = currNode.next;
        }

        return result + "Null";
    }

    public boolean includes(int x) {
        Node currNode = head;
        while (currNode != null)
        {
            if (currNode.value == x)
                return true;
            currNode = currNode.next;
        }
        return false;
    }

    public void insertBefore(int value, int newValue){
        if (head.value == value) {
            insert(newValue);
        } else {
                Node node = new Node(newValue);
                Node current = head;
                while (current.next != null && current.next.value != value) {
                    current = current.next;
                }
                node.next = current.next;
                current.next = node;
            }
    }
}
