/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package array.binary.search;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.Arrays;
import java.util.ArrayList;


public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test public void arrayBinarySearch() {
        int[] test1= {4,8,15,16,23,42};
        int[] test2= {11,22,33,44,55,66,77};
        int expect1 = 4;
        int expect2 = 0;


        System.out.println(Library.BinarySearch(test1,15));

        assertEquals(expect1,Library.BinarySearch(test1,23));
        assertEquals(expect2,Library.BinarySearch(test2,11));

    }
}
