/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package blog3;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        int arr[] = {20,18,12,8,5,-2};
        int n = arr.length;
        QuickSort(arr, 0, n-1);

        System.out.println("QuickSorted array");
        printArray(arr);
    }

    static int partition(int arr[], int left, int right)
    {
        int pivot = arr[right];
        int  low = left - 1;

        for (int i=left; i<right; i++)
        {
            if (arr[i] <= pivot)
            {
                low++;

                Swap(arr, i, low);
            }
        }
        Swap(arr, right, low + 1);

        return low+1;
    }

    static void Swap(int[] arr, int i, int low){
        int temp = arr[i];
        arr[i] = arr[low];
        arr[low] = temp;
    }

    static void QuickSort(int arr[], int left, int right)
    {
        if (left < right)
        {
            int position = partition(arr, left, right);
            QuickSort(arr, left, position-1);
            QuickSort(arr, position+1, right);
        }
    }

    static String printArray(int arr[])
    {
        String result = new String();
        int n = arr.length;
        for (int i=0; i<n; ++i){
            result = arr[i]+" ";
            System.out.print(arr[i]+" ");}
        System.out.println();

        return result;
    }
}
