/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package getEdge;

import org.junit.Before;
import org.junit.Test;

import static getEdge.GetEdge.getEdge;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    Graph<String> g = new Graph<>();

    @Before
    public void setupGraph() {
        Node<String> node1 = g.addNode("Pandora");
        Node<String> node2 = g.addNode("Arendelle");
        Node<String> node3 = g.addNode("Metroville");
        Node<String> node4 = g.addNode("Monstroplolis");
        Node<String> node5 = g.addNode("Narnia");
        Node<String> node6 = g.addNode("Naboo");


        g.addEdge(node1, node2, 150);
        g.addEdge(node2, node3, 99);
        g.addEdge(node1, node3, 82);
        g.addEdge(node2, node4, 42);
        g.addEdge(node3, node4, 105);
        g.addEdge(node6, node4, 73);
        g.addEdge(node3, node6, 26);
        g.addEdge(node3, node5, 37);
        g.addEdge(node5, node6, 250);
    }

    @Test
    public void testGetEdge() {
        String[] cities = {"Metroville", "Pandora"};
        assertEquals(82, getEdge(cities, g));
    }

    @Test
    public void testGetEdge2() {
        String[] cities = {"Naboo", "Pandora"};
        assertEquals(0, getEdge(cities, g));
    }

    @Test
    public void testGetEdge3() {
        String[] cities = {"Narnia", "Arendelle","Naboo"};
        assertEquals(0, getEdge(cities, g));
    }

    @Test
    public void testGetEdge4() {
        String[] cities = {"Arendelle", "Monstroplolis", "Naboo"};
        assertEquals(115, getEdge(cities, g));
    }

}
