/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree.intersection;

import java.util.HashSet;
import java.util.LinkedList;
import java.util.Queue;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }


}
