/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package array.binary.search;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static int BinarySearch(int [] arr, int searchKey){
        if (arr == null) {
            return -1;
        }
        int len = arr.length;
        int i = 0;
        while (i < len) {
            if (arr[i] == searchKey) {
                return i;
            }
            else {
                i = i + 1;
            }
        }
        return -1;
    }
}
