/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package array.shift;

import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.*;
import java.util.ArrayList;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void shiftArray() {
      int[] test1=  {2,4,6,8};
      int[] test2=  {4,8,15,23,42};
      int[] expect1 ={2,4,5,6,8};
      int[] expect2 ={4,8,15,16,23,42};


      assertArrayEquals("test expect output is "+expect1,expect1,Library.addToArray(test1,5));
      assertArrayEquals("test expect output is "+expect2,expect2,Library.addToArray(test2,16));
    }

  }

