/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package data.structure;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void testLibrary(){
        Library currentLibrary = new Library();
//        LinkedList list1 = new LinkedList();

        currentLibrary.insert(1);
        currentLibrary.insert(2);
        currentLibrary.insert(3);

        String expected = "{3} -> {2} -> {1} -> Null";

        assertEquals("Output", expected, currentLibrary.toString());

        assertTrue("true", currentLibrary.includes(1));
        assertFalse("false", currentLibrary.includes(5));
    }
}
